name: 🐛 Bug Report
description: Create a report to help us improve CityPulse.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce it?
      description: Provide steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Browser, Node version, etc.
      placeholder: e.g. macOS 13.0, Chrome 110, Node v18.15.0
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output or screenshots.
      render: shell
